# Generated by Django 5.2 on 2025-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0003_pyme_remove_campaignresources_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='nivelMaduracion',
            field=models.CharField(blank=True, choices=[('inicial', 'Inicial'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='enterprise_type',
            field=models.CharField(blank=True, choices=[('Micro-Pyme', 'Micro-Pyme'), ('PyME', 'PyME'), ('Mediana Tramo 1', 'Mediana Tramo 1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='sector',
            field=models.CharField(blank=True, choices=[('Servicios', 'Servicios'), ('Metalúrgico', 'Metalúrgico'), ('Gráfico', 'Gráfico'), ('Fabrica', 'Fábrica'), ('Textil', 'Textil'), ('Alimentos', 'Alimentos')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='work_type',
            field=models.CharField(choices=[('Transformación Digital', 'Transformación Digital'), ('innovacion', 'Innovación'), ('Sustentabilidad', 'Sustentabilidad')], default='Transformación Digital', max_length=100),
        ),
    ]
