# Generated by Django 5.2 on 2025-08-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0004_pyme_nivelmaduracion_alter_pyme_enterprise_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyme',
            name='work_type',
            field=models.CharField(choices=[('Transformación Digital', 'Transformación Digital'), ('innovación', 'Innovación'), ('Sustentabilidad', 'Sustentabilidad')], default='Transformación Digital', max_length=100),
        ),
    ]
